---
- hosts: c,trapeye,blind,x
  strategy: free
  tasks:
    - name: checks
      ansible.builtin.script: checks.sh
      register: output_checks
    - name: debug
      ansible.builtin.debug: var=output_checks.stdout
    # - name: serial
    #   become: true
    #   shell: "cat /sys/class/dmi/id/product_serial"
    #   register: output_serial
    # - debug: var=output_serial.stdout_lines
    - name: copy the output to a local file
      ansible.builtin.copy:
        content: "{{ output_checks.stdout }}"
        dest: "~/ansible_checks.txt"
        mode: '0644'
      delegate_to: localhost
