---
- hosts: missing
  strategy: linear
  order: inventory
  gather_facts: no
  tasks:
    - name: checks
      shell: "uptime -p &&
        cd ~/code/pats && echo git sha: $(git rev-parse HEAD) &&
        echo image version: $(cat ~/dependencies/image_version) kernel: $(uname -r) $(lsb_release -d) &&
        if [ -e '/dev/baseboard' ] ; then echo 'Baseboard: OK' ; else echo 'Baseboard: NOT DETECTED' ; fi &&
        if [ -e '/dev/pats_mm0' ] ; then echo 'MultiModule: OK' ; else echo 'MultiModule: NOT DETECTED' ; fi &&
        echo RealSense: $(lsusb | grep RealSens) &&
        echo 4G: $(lsusb | grep 'E353/E3131')"
      register: output_checks
    - debug: var=output_checks.stdout_lines
    - name: serial
      become: true
      shell: "cat /sys/class/dmi/id/product_serial"
      register: output_serial
    - debug: var=output_serial.stdout_lines
