---
- hosts: x,c,qc,rc,trapeye,blind
  strategy: free
  tasks:
    - name: checks
      ansible.builtin.script: checks.sh
      register: output_checks
    - name: debug
      ansible.builtin.debug: var=output_checks.stdout
      delegate_to: localhost
