---
- hosts: darkroom
  strategy: free
  tasks:
    - name: Disable all pats daemons
      ansible.builtin.file:
        path: ~/pats/flags/disable
        state: touch
    - name: Kill (auto restart) executor process
      shell: "killall executor || true"
    - name: Pull pats
      git:
        repo: git@github.com:pats-drones/pats.git
        dest: /home/pats/code/pats
        update: yes
        version: luddev
        force: yes
        clone: no
    - name: Build executor
      make:
        chdir: /home/pats/code/pats/base/build
        params:
          NUM_THREADS: 4
    - name: Remove disable flag
      ansible.builtin.file:
        path: ~/pats/flags/disable
        state: absent
