// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file TFMessagePublisher.h
 * This header file contains the declaration of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _TF2_MSGS_MSG_TFMESSAGE_PUBLISHER_H_
#define _TF2_MSGS_MSG_TFMESSAGE_PUBLISHER_H_

#include <fastrtps/fastrtps_fwd.h>
#include <fastrtps/publisher/PublisherListener.h>

#include "TFMessagePubSubTypes.h"

class TFMessagePublisher 
{
public:
	TFMessagePublisher();
	virtual ~TFMessagePublisher();
	bool init();
    void run();
    void add_transform(double trans_x, double trans_y, double trans_z, double rot_x, double rot_y, double rot_z, double rot_w, int64_t time, std::string source, std::string target, bool is_static = false);
    void clear_transforms();

private:
    eprosima::fastrtps::Participant *mp_participant;
    eprosima::fastrtps::Publisher *mp_publisher;
    eprosima::fastrtps::Publisher *mp_publisher_static;

    std::vector<geometry_msgs::msg::TransformStamped> transforms;
    std::vector<geometry_msgs::msg::TransformStamped> transforms_static;

	class PubListener : public eprosima::fastrtps::PublisherListener
	{
	public:
		PubListener() : n_matched(0){};
		~PubListener(){};
		void onPublicationMatched(eprosima::fastrtps::Publisher* pub,eprosima::fastrtps::rtps::MatchingInfo& info);
		int n_matched;
	} m_listener;
	tf2_msgs::msg::TFMessagePubSubType myType;
};

#endif // _TF2_MSGS_MSG_TFMESSAGE_PUBLISHER_H_
