png:
	python3 create_dronenavigation.py
	dot -Tpng dronenavigation.gv -o dronenavigation.png
	python3 create_dronecontroller.py
	dot -Tpng dronecontroller.gv -o dronecontroller.png

install_requirements:
	sudo apt install graphviz	
