clear
close all
%% Import data from text file.
% Script for importing data from the following text file:
%
%    I:\share\mu-g\SLAMdunk\build\log.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/18 14:46:01

%% Initialize variables.
filename = './build-pc-Desktop_Qt_5_9_1_GCC_64bit-Debug/log.txt';
delimiter = ';';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ID = dataArray{:, 1};
imLx = dataArray{:, 2};
imLy = dataArray{:, 3};
imRx = dataArray{:, 4};
imRy = dataArray{:, 5};
valid = dataArray{:, 6};
posErrX = dataArray{:, 7};
posErrY = dataArray{:, 8};
posErrZ = dataArray{:, 9};
velX = dataArray{:, 10};
velY = dataArray{:, 11};
velZ = dataArray{:, 12};
hoverthrottle = dataArray{:, 13};
autoThrottle = dataArray{:, 14};
autoRoll = dataArray{:, 15};
autoPitch = dataArray{:, 16};
autoYaw = dataArray{:, 17};
joyThrottle = dataArray{:, 18};
joyRoll = dataArray{:, 19};
joyPitch = dataArray{:, 20};
joyYaw = dataArray{:, 21};
joySwitch = dataArray{:, 22};
throttleP = dataArray{:, 23};
throttleI = dataArray{:, 24};
throttleD = dataArray{:, 25};
dt = dataArray{:, 26};
dx = dataArray{:, 27};
dy = dataArray{:, 28};
dz = dataArray{:, 29};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
%%derive / calc some stuff:
A(:,1) = posErrY ; 
A(:,2) = 0;
A(:,3) = -(autoThrottle - 1580) / (1650 - 1580) - 2.5; %heuristically scaled!
A(:,4) = joySwitch ; 

subplot(3,1,1)
plot(A)
legend('PosErrY [m]','Pos setpoint','- scaled throttle', 'Stabilization ON')
subplot(3,1,2)
hold on
plot(velY)
legend('velocity Y')
subplot(3,1,3)
plot(hoverthrottle)
legend('hover throttle')

figure;
title positions
subplot(3,1,1); plot(posErrX); legend('x')
subplot(3,1,2); plot(posErrY); legend('y')
subplot(3,1,3); plot(posErrZ); legend('z')

figure;
scatter3(posErrX,posErrY,posErrZ)


