clear
close all
%% Import data from text file.
% Script for importing data from the following text file:
%
%    I:\share\mu-g\SLAMdunk\build\log.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/18 13:49:52

%% Initialize variables.
filename = 'I:\share\mu-g\SLAMdunk\build\log.txt';
delimiter = ';';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
imLx = dataArray{:, 1};
imLy = dataArray{:, 2};
imRx = dataArray{:, 3};
imRy = dataArray{:, 4};
valid = dataArray{:, 5};
posErrX = dataArray{:, 6};
posErrY = dataArray{:, 7};
posErrZ = dataArray{:, 8};
velX = dataArray{:, 9};
velY = dataArray{:, 10};
velZ = dataArray{:, 11};
hoverthrottle = dataArray{:, 12};
autoThrottle = dataArray{:, 13};
autoRoll = dataArray{:, 14};
autoPitch = dataArray{:, 15};
autoYaw = dataArray{:, 16};
joyThrottle = dataArray{:, 17};
joyRoll = dataArray{:, 18};
joyPitch = dataArray{:, 19};
joyYaw = dataArray{:, 20};
joySwitch = dataArray{:, 21};
throttleP = dataArray{:, 22};
throttleI = dataArray{:, 23};
throttleD = dataArray{:, 24};
dt = dataArray{:, 25};
dx = dataArray{:, 26};
dy = dataArray{:, 27};
dz = dataArray{:, 28};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%%derive / calc some stuff:
A(:,1) = posErrY ; 
A(:,2) = 0;
A(:,3) = -(autoThrottle - 1580) / (1650 - 1580) - 2.5; %heuristically scaled!
A(:,4) = joySwitch ; 

subplot(3,1,1)
plot(A)
legend('PosErrY [m]','Pos setpoint','- scaled throttle', 'Stabilization ON')
subplot(3,1,2)
hold on
plot(velY)
legend('velocity Y')
subplot(3,1,3)
plot(hoverthrottle)
legend('hover throttle')